### ISSUE TITLE
Subtract from Res

### ISSUE THREAD

**Issue by JaredCrean2** [OptimalDesignLab/SummationByParts.jl#2]
For the Euler equations, the boundry integration term needs to be subtracted from the array res, not added to it.  For now I made a new function, boundaryintegrate2!, in my local copy of SummationByParts, but a more permanent solution is needed.  This also brings up the question of how to (elegantly) support different operators (not just += and -=), and how to handle applying transposed operators or the non transposed version.  My guess is that some kind of metaprogramming is the answer, but I don't know exactly what kind.

**Comment by JaredCrean2** [comment]
Bump.  There are a couple ways to solve this.  The fastest way is to have the SBP function take in an untyped argument that is really a functor that can apply any arbitrary transformation to the result of the SBP operation just before adding it to `res`.  In this case, the update to `res` would like like:

``` julia
function volumeintegrate!(flux::AbstractArray, other_args..., res::AbstractArray, update_functor)
#... do function work here....
res[i, j, k] += update_functor(final_val)
end
```

This way `update_functor` could be the unary minus operation, or any other arbitrary tranformation applied to `final_val`.  

The other option is to just pass in a variable to multiply the `final_val` by, but that would be a floating point operation, whereas using a functor to do `-final_val` is the unary minus operation, which is a much less expensive flipping of the sign bit.

**Comment by jehicken** [comment]
This should be optional.  Is there a way to provide a default functor here?

**Comment by JaredCrean2** [comment]
You can have a default argument.  You will have to define this no-op functor inside SBP and use it as you would any other default argument
